# Generated by Django 2.2 on 2019-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(default=500)),
                ('Gender', models.TextField()),
                ('Age', models.IntegerField(default=170)),
                ('Salary', models.FloatField(blank=True, default=None, null=True)),
                ('Loan_amount', models.FloatField(blank=True, default=None, null=True)),
                ('Term', models.IntegerField(default=170)),
            ],
        ),
    ]
