# Generated by Django 2.2 on 2019-04-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Age',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='ID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Term',
            field=models.IntegerField(default=900),
        ),
    ]
